"""
V2.11 Report Delivery — Webhook + Email
=========================================
Sends daily eval reports via WeCom webhook and/or SMTP email.
"""

import os
import smtplib
import json
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path

import requests


# ── Config ──────────────────────────────────────────
WECOM_WEBHOOK_URL = os.environ.get(
    "WECOM_WEBHOOK_URL",
    ""  # Set this to your WeCom bot webhook key
)

SMTP_CONFIG = {
    "host": os.environ.get("SMTP_HOST", "smtp.qq.com"),
    "port": int(os.environ.get("SMTP_PORT", "587")),
    "user": os.environ.get("SMTP_USER", ""),
    "password": os.environ.get("SMTP_PASSWORD", ""),
    "from_addr": os.environ.get("SMTP_FROM", ""),
    "to_addr": os.environ.get("SMTP_TO", ""),
}


# ── Report Formatter ────────────────────────────────
def format_markdown_report(report: dict) -> str:
    """Format a daily eval report as markdown for WeCom/Mail."""
    s = report["summary"]
    h = report["health"]

    lines = [
        "# 🧠 OpenClaw Daily Self-Cure Report",
        f"**Date**: {report['date']}",
        f"**Status**: {'🟢 ALL GREEN' if s['all_green'] else '🔴 FAILURES'}",
        "",
        "## 📊 Eval Results",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total Tests | {s['total_tests']} |",
        f"| Passed | {s['passed']} |",
        f"| Failed | {s['failed']} |",
        f"| Score | {s['passed']}/{s['total_tests']} |",
        "",
    ]

    if report.get("evals"):
        lines.append("## 🔍 Suite Details")
        lines.append("")
        for e in report["evals"]:
            suite_name = e.get("suite", "unknown").replace(".py", "")
            passed = e.get("passed", 0)
            failed = e.get("failed", 0)
            status = "✅" if e.get("all_green") else "❌"
            lines.append(f"- {status} **{suite_name}**: {passed}P / {failed}F")

        lines.append("")

    lines.extend([
        "## 🏥 System Health",
        f"- Docker: {'🟢 running' if h.get('docker_running') else '🔴 stopped'}",
        f"- Git: {'dirty' if h.get('git_dirty') else 'clean'}",
        f"- Skills: {h.get('skill_count', '?')} loaded",
        "",
        "---",
        "*Generated by V2.11 Daily Eval Reporter*",
    ])

    return "\n".join(lines)


# ── WeCom Webhook ───────────────────────────────────
def send_wecom_report(report: dict) -> bool:
    """Send report via WeCom webhook."""
    if not WECOM_WEBHOOK_URL:
        print("  [SKIP] WECOM_WEBHOOK_URL not set")
        return False

    content = format_markdown_report(report)

    payload = {
        "msgtype": "markdown",
        "markdown": {
            "content": content,
        },
    }

    try:
        r = requests.post(WECOM_WEBHOOK_URL, json=payload, timeout=10)
        if r.status_code == 200:
            resp = r.json()
            if resp.get("errcode") == 0:
                print(f"  ✅ WeCom report sent")
                return True
            else:
                print(f"  ❌ WeCom API error: {resp}")
                return False
        else:
            print(f"  ❌ WeCom HTTP {r.status_code}: {r.text[:200]}")
            return False
    except Exception as e:
        print(f"  ❌ WeCom send failed: {e}")
        return False


# ── SMTP Email ──────────────────────────────────────
def send_email_report(report: dict) -> bool:
    """Send report via SMTP email."""
    cfg = SMTP_CONFIG
    if not cfg["user"] or not cfg["password"]:
        print("  [SKIP] SMTP credentials not set")
        return False

    content = format_markdown_report(report)
    html_content = content.replace("\n", "<br>\n")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🧠 OpenClaw Daily Report — {report['date']} {'✅' if report['summary']['all_green'] else '❌'}"
    msg["From"] = cfg["from_addr"]
    msg["To"] = cfg["to_addr"]

    msg.attach(MIMEText(content, "plain", "utf-8"))
    msg.attach(MIMEText(f"<html><body><pre>{html_content}</pre></body></html>", "html", "utf-8"))

    try:
        with smtplib.SMTP(cfg["host"], cfg["port"], timeout=15) as server:
            server.starttls()
            server.login(cfg["user"], cfg["password"])
            server.send_message(msg)
        print(f"  ✅ Email report sent to {cfg['to_addr']}")
        return True
    except Exception as e:
        print(f"  ❌ Email send failed: {e}")
        return False


# ── Main delivery function ──────────────────────────
def deliver_report(report: dict) -> dict:
    """Try all delivery channels, return status map."""
    results = {}

    if WECOM_WEBHOOK_URL:
        results["wecom"] = send_wecom_report(report)
    else:
        results["wecom"] = "skipped (no config)"

    if SMTP_CONFIG["user"] and SMTP_CONFIG["password"]:
        results["email"] = send_email_report(report)
    else:
        results["email"] = "skipped (no config)"

    return results


# ── CLI ─────────────────────────────────────────────
if __name__ == "__main__":
    import sys

    # Test with a stub report
    stub = {
        "date": "2026-06-23",
        "summary": {
            "total_tests": 11,
            "passed": 11,
            "failed": 0,
            "all_green": True,
        },
        "health": {
            "docker_running": True,
            "git_dirty": False,
            "skill_count": 148,
        },
        "evals": [
            {"suite": "test_self_coder.py", "passed": 5, "failed": 0, "all_green": True},
            {"suite": "test_extended.py", "passed": 6, "failed": 0, "all_green": True},
        ],
    }

    print("=== Markdown Report Preview ===\n")
    print(format_markdown_report(stub))
    print("\n=== Delivery Attempt ===")
    results = deliver_report(stub)
    print(json.dumps(results, indent=2))
